In [1]:
#1.How do you create a NumPy array from the list [1, 2, 3, 4, 5]?

import numpy as np


In [2]:
l = [1,2,3,4,5]

In [3]:
l

[1, 2, 3, 4, 5]

In [4]:
arr = np.array(l)
arr

array([1, 2, 3, 4, 5])

In [5]:
#2.What is the output of np.array([10, 20, 30, 40])[2]?

arr1 =np.array([10,20,30,40])

arr1[2]


np.int64(30)

In [6]:

#3.Create a NumPy array containing integers from 1 to 10.

import numpy as np

a = np.arange(1,11)

print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [7]:
#4.Create a NumPy array containing five zeros.

arrr = np.zeros(5)

print(arrr)

[0. 0. 0. 0. 0.]


In [8]:
# 5.Create a 3 × 3 NumPy array containing only ones.

a1 = np.ones((3,3))

print(a1)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [9]:
a1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
# 6.What is the shape of np.array([[1, 2, 3], [4, 5, 6]])?

a2 = np.array([[1,2,3],[4,5,6]])

a2.shape


(2, 3)

In [11]:
#7.What is the number of dimensions of np.array([[1, 2], [3, 4], [5, 6]])?

a3 = np.array ([[1,2],[3,4],[5,6]])

a3.ndim

2

In [12]:
# 8.Given arr = np.array([10, 20, 30, 40, 50]), extract the elements from index 1 to index 3.

arr1


array([10, 20, 30, 40])

In [13]:
arr1[1:3]

array([20, 30])

In [14]:
print(arr1[1:3])

[20 30]


In [15]:
# 9.Given arr = np.array([1, 2, 3, 4, 5]), multiply every element by 10.

print(arr)

arr * 10


[1 2 3 4 5]


array([10, 20, 30, 40, 50])

In [16]:
#10.Find the sum, mean, maximum, and minimum of np.array([12, 5, 8, 20, 15]).

arr1 = np.array([12,5,8,20,15])

arr1


array([12,  5,  8, 20, 15])

In [17]:
#finding sum from abytearray

print(arr1.sum())

60


In [18]:
#finding mean value from abytearray

print(arr1.mean())

12.0


In [19]:
#finding maximum value from array

print(arr1.max())

20


In [20]:
#finding minimum value from array

print(arr1.min())

5


In [21]:
#11.Given arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]), extract only the even numbers.

a


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
print(a[a % 2 == 0])

[ 2  4  6  8 10]


In [23]:
#12.Sort np.array([5, 2, 8, 1, 9, 3]) in ascending order.

arra = np.array([5,2,8,1,9,3])

print(np.sort(arra))


[1 2 3 5 8 9]


In [24]:
#13.Find the indices of elements greater than 50 in np.array([10, 60, 30, 80, 45, 90]).

arru = np.array([10,60,30,80,45,90])

print(np.where(arru>50)[0])


[1 3 5]


In [25]:
#14.Reshape np.array([1, 2, 3, 4, 5, 6]) into a 2 × 3 array.

arra2 = np.array([1,2,3,4,5,6])

print(arra2.reshape(2,3))

[[1 2 3]
 [4 5 6]]


In [26]:
#15.Given two arrays [1, 2, 3] and [4, 5, 6], perform element-wise addition, subtraction, multiplication, and division.

p1 = np.array([1,2,3])

p2 = np.array([4,5,6])

p1 + p2

array([5, 7, 9])

In [27]:
print(p1 - p2)

[-3 -3 -3]


In [28]:
print(p1 * p2)

[ 4 10 18]


In [29]:
print(p1 / p2)

[0.25 0.4  0.5 ]


In [30]:
#16.Perform matrix multiplication on [[1, 2], [3, 4]] and [[5, 6], [7, 8]].

a4 = np.array([[1,2],[3,4]])

b5 = np.array([[5,6],[7,8]])

result = np.matmul(a4,b5)

print(result)


[[19 22]
 [43 50]]


In [31]:
# 17.Find the transpose of [[1, 2, 3], [4, 5, 6]]

myarr=np.array([[1,2,3],[4,5,6]])

print(myarr.transpose())

[[1 4]
 [2 5]
 [3 6]]


In [32]:
# 18.Replace all values greater than 3 with 100 in np.array([1, 2, 3, 4, 5]).


ara=np.array([1,2,3,4,5])
ara[ara>3]=100

print(ara)

[  1   2   3 100 100]


In [33]:
# 19.Create a 5 × 5 array containing numbers from 1 to 25 and extract the second row and third column.

aarrr=np.arange(1,26).reshape(5,5)

print(aarrr)

print("second Row :",aarrr[1])
print("Third column : ",aarrr[:,2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
second Row : [ 6  7  8  9 10]
Third column :  [ 3  8 13 18 23]


In [34]:
# 20.Given [[10, 20, 30], [40, 50, 60], [70, 80, 90]], find the row sums, column sums, overall mean, and elements greater than 45.

my_arr = np.array([[10,20,30],[40,50,60],[70,80,90]])

print(my_arr)
print("Row sum :",np.sum(my_arr,axis=1))
print("Column sum :",np.sum(my_arr,axis=0))
print("Overall mean : ",np.mean(my_arr))
print("elements greater than 45 :",my_arr[my_arr>45])


[[10 20 30]
 [40 50 60]
 [70 80 90]]
Row sum : [ 60 150 240]
Column sum : [120 150 180]
Overall mean :  50.0
elements greater than 45 : [50 60 70 80 90]


In [35]:
# 21.Create a NumPy array containing all even numbers from 2 to 20.

a21=np.arange(2,21,2)

print(a21)

[ 2  4  6  8 10 12 14 16 18 20]


In [36]:
# 22.Create a NumPy array containing 10 equally spaced values between 0 and 1.

a22=np.linspace(0,1,10)
print(a22)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [37]:
#23.Given arr = np.array([3, 7, 2, 9, 4, 8]), find the index of the maximum value.

a23=np.array([3,7,2,9,4,8])
print(np.argmax(a23))

3


In [38]:
#24.Given arr = np.array([10, 20, 30, 40, 50]), reverse the array.

a24=np.array([10,20,30,40,50])
print(a24)
print(a24[::-1])

[10 20 30 40 50]
[50 40 30 20 10]


In [39]:
# 25.Find the unique values in np.array([1, 2, 2, 3, 4, 4, 5])

a25=np.array([1,2,2,3,4,4,5])

print(np.unique(a25))

[1 2 3 4 5]


In [40]:
# 26.Count how many elements are greater than 25 in np.array([10, 30, 15, 40, 25, 50]).

a26 =np.array([10,30,15,40,25,50])

print(np.sum(a26>25))

3


In [41]:
# 27.Convert the following 1D array into a 3 × 3 array: np.array([1,2,3,4,5,6,7,8,9]).

a27 =np.array([1,2,3,4,5,6,7,8,9])
print(a27.reshape(3,3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [42]:
# 28.Flatten the array [[1, 2], [3, 4], [5, 6]] into a 1D array.

a28 = np.array([[1,2],[3,4],[5,6]])

print(a28.flatten())

[1 2 3 4 5 6]


In [43]:
# 29.Concatenate np.array([1,2,3]) and np.array([4,5,6]).

p = np.array([1,2,3])

q = np.array([4,5,6])

print(np.concatenate((p,q)))

[1 2 3 4 5 6]


In [44]:
# 30.Split np.array([1,2,3,4,5,6]) into three equal parts.

a30 = np.array([1,2,3,4,5,6])

print(np.split(a30,3))

[array([1, 2]), array([3, 4]), array([5, 6])]


In [45]:
# 31.Find the standard deviation of np.array([10, 20, 30, 40, 50]).

a31 = np.array([10,20,30,40,50])

print(np.std(a31))

14.142135623730951


In [46]:
# 32.Find the variance of np.array([2, 4, 6, 8, 10]).


a32=np.array([2,4,6,8,10])

print(np.var(a32))

8.0


In [47]:
# 33.Given arr = np.array([1, 2, 3, 4, 5]), calculate the cumulative sum.
print(arr)

print(np.cumsum(arr))



[1 2 3 4 5]
[ 1  3  6 10 15]


In [48]:
# 34.Given arr = np.array([1, 2, 3, 4, 5]), calculate the cumulative product.

print(arr)
np.cumprod(arr)

[1 2 3 4 5]


array([  1,   2,   6,  24, 120])

In [49]:
# 35.Replace all odd numbers with -1 in np.array([1,2,3,4,5,6,7]).

a35 = np.array([1,2,3,4,5,6,7])
print(a35)
a35[a35%2 !=0]=-1

print(a35)

[1 2 3 4 5 6 7]
[-1  2 -1  4 -1  6 -1]


In [50]:
# 36.Find the maximum value in each row of [[1,5,3],[8,2,6],[4,9,7]].

a36 = np.array([[1,5,3],
                [8,2,6],
                [4,9,7]])


print(np.max(a36,axis=1))

[5 8 9]


In [51]:
# 37.Find the minimum value in each column of [[5,2,8],[1,7,3],[6,4,9]].

a37 = np.array([[5,2,8],
                [1,7,3],
                [6,4,9]])

print(np.min(a37,axis=0))

[1 2 3]


In [52]:
# 38.Create a 4 × 4 identity matrix using NumPy.

a38 = np.eye(4)
print(a38)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [53]:
#39.Generate a 3 × 3 matrix of random integers between 1 and 20.

a39=np.random.randint(1,21,size=(3,3))
print(a39)

[[17  8  4]
 [ 9 12 20]
 [ 8 18  5]]


In [54]:
#40.Given two NumPy arrays, find the elements that are common to both arrays.

y = np.array([1,2,3,4,5])
z = np.array([3,4,5,6,7])

print(np.intersect1d(y,z))

[3 4 5]



***Exercises.***


In [55]:
# 1.Get the shape of the matrix.
l=[[18,66,90],[17,88,86],[19,78,80]]
exe=np.array(l)

print(exe)

exe.shape

[[18 66 90]
 [17 88 86]
 [19 78 80]]


(3, 3)

In [56]:
# 2.Find the average age of students 

exe[:,0].mean()
print("Average age of student is : ",exe[:,0].mean())

Average age of student is :  18.0


In [57]:
# 3.Extract the Math marks of all student

print("Maths marks of all students :",exe[:,1])

Maths marks of all students : [66 88 78]


In [58]:
# 4.Find the highest science marks 

print("Highest science marks :",exe[:,2].max())

Highest science marks : 90


In [59]:
# 5. Get the details of the student who scored more than 80 in maths
print("Details of student who scored more than 80 in maths :")
exe[exe[:,1]>80]

Details of student who scored more than 80 in maths :


array([[17, 88, 86]])

In [60]:
# 6.Increase the maths marks of all student by 5 

print("Increasing the maths marks of all students : ")

exe[:,1]=exe[:,1] + 5

print(exe)

Increasing the maths marks of all students : 
[[18 71 90]
 [17 93 86]
 [19 83 80]]


In [61]:
# 7. Find how many students are younger than 19.a

print("How many students are younger than 19 :")

print(exe[exe[:,0] < 19])

How many students are younger than 19 :
[[18 71 90]
 [17 93 86]]


In [62]:
# 8. Calculate the average marks in each subject (Colum-wise mbreakpoint)

print("Calculating the average marks of each subject : ")

print("Maths avg_marks =",exe[:,1].mean())
print("Science avg_marks =",exe[:,2].mean())

Calculating the average marks of each subject : 
Maths avg_marks = 82.33333333333333
Science avg_marks = 85.33333333333333


In [63]:
# 9. Get the data of the student who scored at least 80 in both subjects 

l=[[17,80,80],[18,90,86],[19,76,73]]

data=np.array(l)
result = data[(data[:,1]>=80) & (data[:,2]>=80)]

print(result)

[[17 80 80]
 [18 90 86]]


In [64]:
# 10. Replace all science marks below 75 with 0. 

data[data[:,2]<75,2]=0
print(data)

[[17 80 80]
 [18 90 86]
 [19 76  0]]
